##############################################
#          Aurum Configuration File          #
##############################################

general:
  # World name, x, y, z, yaw, pitch
  per-warp-perms: false # If true, a warp xyz would require the permission aurum.warp.xyz to use.
  stack-default-quanity: 1
  compact-playerlist: false # Recomeneded for larger servers

chat:
  # %prefix%  - The prefix of the user, supplied by PermissionsEX.
  # %color%   - The 'color' option of the player's group, meant to be its thematic color.
  # %sender%   - The message-sender's display name.
  # %target%   - The target of the message, if applicable.
  # %suffix%  - The suffix of the user, supplied by PermissionsEX.
  # %message% - The message's content.
  format:
    normal: "%prefix%%name%&f: %message%"
    message-in: "%prefix%%sender% &7-> You&f: %message%"
    message-out: "&7You -> &f%prefix%%target%&f: %message%"
  nickname-prefix: ""

data:
  spawn: null
  warps: null