##############################################
#          Aurum Configuration File          #
##############################################

general:
  # World name, x, y, z, yaw, pitch
  per-warp-perms: false # If true, a warp xyz would require the permission aurum.warp.xyz to use.
  stack-default-quanity: 1
  compact-playerlist: false # Recomeneded for larger servers

chat:
  # %name% The here-configured display name of players.
  # %prefix%  - The prefix of the user, supplied by PermissionsEX.
  # %color%   - The 'color' option of the player's group, meant to be its thematic color.
  # %sender%   - The relevant player's username.
  # %suffix%  - The suffix of the user, supplied by PermissionsEX.
  # %message% - The message's content.
  display-name: "{prefix}{name}"
  nickname-prefix: ""
  format:
    normal: "{name}&f: {message}"
    message-in: "{name} &7-> You&f: {message}"
    message-out: "&7You -> &f{name}&f: {message}"

data:
  spawn: null
  warps: null