name: Aurum
description: An essentials alternative for project poseidon.
main: org.whoisjeb.aurum.Aurum
version: 1.0.0-SNAPSHOT
authors:
  - WhoIsJeb
depend:
  - PermissionsEx

commands:
  spawn:
    description: Warps the user to spawn.
    usage: /<command>
    permission: aurum.spawn
    permission-message: You are not authorized to warp to spawn.
  setspawn:
    description: Sets spawn to the user's location.
    usage: /<command>
    permission: aurum.setspawn
    permission-message: You are not authorized to warp to spawn.
  rules:
    description: Displays the server rules.
    usage: /<command>
    permission: aurum.rules
    permission-message: You are not authorized to view the server rules.
  discord:
    description: Links to the server's discord.
    usage: /<command>
    permission: aurum.discord
    permission-message: You are not authorized to view the server's discord invite.

permissions:
  aurum.player:
    description: Gives access to Aurum's essential commands.
    children:
      aurum.spawn: true
      aurum.rules: true
      aurum.discord: true
  aurum.spawn:
    description: Grants access to /spawn.
    default: not op
  aurum.setspawn:
    description: Grants access to /setspawn.
    default: op
  aurum.rules:
      description: Grants access to /rules.
      default: not op
  aurum.color:
    description: Allows the usage of color codes.
    default: op