name: Aurum
description: An essentials alternative for project poseidon.
main: org.whoisjeb.aurum.Aurum
version: 1.0.0-SNAPSHOT
authors:
  - WhoIsJeb
depend:
  - PermissionsEx

commands:
  spawn:
    description: Warps the sender to spawn.
    usage: /<command>
    permission: aurum.spawn
    permission-message: You are not authorized to execute /spawn!
  setspawn:
    description: Sets spawn to the user's location.
    usage: /<command>
    permission: aurum.setspawn
    permission-message: You are not authorized to execute /setspawn!
  rules:
    description: Displays the server rules.
    usage: /<command>
    permission: aurum.rules
    permission-message: You are not authorized to execute /rules!
  discord:
    description: Links to the server's discord.
    usage: /<command>
    permission: aurum.discord
    permission-message: You are not authorized to execute /discord!
  sethome:
    description: Sets a new home at the sender's position.
    usage: /<command>
    permission: aurum.home
    permission-message: You are not authorized to execute /sethome!
  home:
    description: Warps the sender to the specified home.
    usage: /<command>
    permission: aurum.home
    permission-message: You are not authorized to execute /home!
  delhome:
    description: Deletes the specified home.
    usage: /<command>
    permission: aurum.home
    permission-message: You are not authorized to execute /delhome!
  homes:
    description: Lists the sender's homes.
    usage: /<command>
    permission: aurum.home
    permission-message: You are not authorized to execute /homes!
  warp:
    description: Teleports the sender to the specified warp.
    usage: /<command> <warp>
    permission: aurum.warp
    permission-message: You are not authorized to execute /warp!
  warps:
    description: Lists the server's warps.
    usage: /<command> <warp>
    permission: aurum.warp
    permission-message: You are not authorized to execute /warp!
  setwarp:
    description: Sets a new warp at the sender's position.
    usage: /<command> <warp>
    permission: aurum.setwarp
    permission-message: You are not authorized to execute /setwarp!
  delwarp:
    description: Deletes the specified warp.
    usage: /<command>
    permission: aurum.delwarp
    permission-message: You are not authorized to execute /delwarp!

permissions:
  aurum.player:
    description: Gives access to Aurum's essential commands.
    children:
      aurum.spawn: true
      aurum.rules: true
      aurum.discord: true
      aurum.home: true
  aurum.spawn:
    description: Grants access to /spawn.
    default: not op
  aurum.setspawn:
    description: Grants access to /setspawn.
    default: op
  aurum.rules:
    description: Grants access to /rules.
    default: not op
  aurum.home:
    description: Grants access to the homes commands.
    default: op
  aurum.color:
    description: Allows the usage of color codes.
    default: op
  aurum.warp:
    description: Grants access to /warp and /warps.
    default: not op
  aurum.setwarp:
    description: Grants access to /setwarp.
    default: op
  aurum.delwarp:
    description: Grants access to /delwarp.
    default: op