name: Aurum
description: An essentials alternative for project poseidon.
main: org.whoisjeb.aurum.Aurum
version: 1.0.0-SNAPSHOT
authors:
  - coffeelover42
depend:
  - PermissionsEx

commands:
  aurum:
    description: Display plugin's info, or reloads its data.
    aliases: [au]
    usage: /aurum [reload|info]
    permission: aurum.aurum
  balance:
    description: Prints the sender's or another's balance.
    aliases: [bal, bla, money]
    usage: /balance [player]
    permission: aurum.balance
  balancetop:
    description: Displays a page of the richest players.
    aliases: [baltop, blatop, baltpo, blatpo]
    usage: /balancetop [page]
    permission: aurum.balance
  ban:
    description: Bans the specified user.
    usage: /ban <player> [erason]
    permission: aurum.ban
  banlist:
    description: Prints a page of currently active bans.
    usage: /banlist [page]
    permission: aurum.ban
  banlog:
    description: Prints a page of past bans, active or not.
    usage: /banlog [page]
    permission: aurum.ban
  delhome:
    description: Deletes the specified home.
    aliases: [delh]
    usage: /delhome <home>
    permission: aurum.home
  delwarp:
    description: Deletes the specified warp.
    usage: /delwarp <warp>
    permission: aurum.delwarp
  discord:
    description: Links to the server's discord.
    usage: /discord
    permission: aurum.discord
  economy:
    description: Allows for managing the server economy.
    aliases: [eco, econ]
    usage: /economy <give|take|set> <player> <amount>
    permission: aurum.economy
  grounditemclear:
    description: Clears all ground items.
    aliases: [itemclear, iclear, gic, giclear]
    usage: /gic
    permission: aurum.grounditemclear
  heal:
    description: Heals the sender or a target.
    usage: /heal [player]
    permission: aurum.heal
  help:
    description: Displays available commands.
    aliases: [?, hlep]
    usage: /help [page|plugin]
    permission: aurum.help
  home:
    description: Warps the sender to the specified home.
    aliases: [h, hmoe, hoem]
    usage: /home <home>
    permission: aurum.home
  homes:
    description: Lists the sender's or target's homes.
    usage: /homes [player]
    permission: aurum.home
  importzcore:
    description: Imports data from ZCore into Aurum.
    usage: /importzcore
    permission: aurum.importzcore
  item:
    description: Gives the sender or target an item.
    aliases: [i]
    usage: /item <item> [quanity]
    permission: aurum.item
  killall:
    description: Kills hostile and/or passive mobs.
    aliases: [killa, ka, purge, pruge]
    usage: /killall [all|passive|hostile]
    permission: aurum.killall
  modview:
    description: Displays info on a player.
    aliases: [modv]
    usage: /modview [player]
    permission: aurum.modview
  motd:
    description: Prints the server's MOTD.
    usage: /motd
    permission: aurum.motd
  mute:
    description: Mutes the target.
    usage: /mute <player>
    permission: aurum.mute
  nickname:
    description: Changes the sender's or another's nickname.
    aliases: [nick, ncik]
    usage: /nickname <nickname|"clear"> [player]
    permission: aurum.nickname
  offlineteleport:
    description: Teleports the sender to an offline player.
    aliases: [offlinetp, otp]
    usage: /otp <player>
    permission: aurum.teleport
  pay:
    description: Sends the target an amount of money.
    usage: /pay <player> <amount>
    permission: aurum.pay
  playerlist:
    description: Lists the currently online players.
    aliases: [list, who]
    usage: /playerlist
    permission: aurum.playerlist
  rules:
    description: Displays the server rules.
    aliases: [rlues]
    usage: /rules
    permission: aurum.rules
  sethome:
    description: Sets a new home at the sender's position.
    aliases: [seth]
    usage: /sethome <home>
    permission: aurum.home
  setspawn:
    description: Sets spawn to the sender's position.
    aliases: [setsapwn, setspanw]
    usage: /setspawn
    permission: aurum.setspawn
  setwarp:
    description: Sets a new warp at the sender's position.
    usage: /setwarp <warp>
    permission: aurum.setwarp
  spawn:
    description: Warps the sender to spawn.
    aliases: [sapwn, spanw]
    usage: /spawn
    permission: aurum.spawn
  sudo:
    description: Forces one to chat or run a command.
    usage: /sudo <victim> <command|c:message>
    permission: aurum.sudo
  teleport:
    description: TP's  the sender to a player or position.
    aliases: [tp]
    usage: /tp <player|x, y, z>
    permission: aurum.teleport
  teleportaccept:
    description: Accepts a teleport request.
    aliases: [tpaccept, tpac]
    usage: /tpaccept [player]
    permission: aurum.teleportask
  teleportask:
    description: Requests that the sender tp to the target.
    aliases: [tpa]
    usage: /tpa <player>
    permission: aurum.teleportask
  teleportaskhere:
    description: Requests that the target tp to the sender.
    aliases: [tpahere, tpah]
    usage: /tpahere <player>
    permission: aurum.teleportask
  teleportdeny:
    description: Denies a teleport request.
    aliases: [tpdeny, tpd, tpad]
    usage: /tpdeny [player]
    permission: aurum.teleportask
  tellraw:
    description: Prints what is typed after /tellraw.
    aliases: [tr]
    usage: /tellraw <message>
    permission: aurum.tellraw
  time:
    description: Changes the time to the specified time.
    aliases: [settime, timeset]
    usage: /time <day|night|dawn|dusk>
    permission: aurum.time
  unban:
    description: Unbans the target.
    usage: /unban <player>
    permission: aurum.ban
  unmute:
    description: Unmutes the target.
    usage: /unban <player>
    permission: aurum.mute
  unwarn:
    description: Removes a warning from the specified user.
    usage: /unwarn <player> <reason>
    permission: aurum.warn
  warn:
    description: Warns the target.
    usage: /warn <player> [reason]
    permission: aurum.warn
  warp:
    description: TP's the sender to the specified warp.
    usage: /warp <warp>
    permission: aurum.warp
  warps:
    description: Lists the server's warps.
    usage: /warps
    permission: aurum.warp
  weather:
    description: Changes the weather.
    aliases: [setweather, weatherset]
    usage: /weather [clear|rain]
    permission: aurum.weather
  whois:
    description: Prints the username of an nick'd player.
    aliases: [realname, whos]
    usage: /whois <nickname>
    permission: aurum.whois

permissions:
  aurum.player:
    description: Gives access to Aurum's essential commands.
    children:
      aurum.help: true
      aurum.spawn: true
      aurum.rules: true
      aurum.discord: true
      aurum.playerlist: true
      aurum.motd: true
      aurum.home: true
      aurum.warp: true
      aurum.teleportask: true
  aurum.aurum:
    description: Grants access to /aurum.
    default: not op
  aurum.balance:
    description: Grants access to /balance and /baltop.
    default: op
  aurum.killall:
    description: Grants access to /killall.
    default: op
  aurum.help:
    description: Grants access to /help.
    default: not op
  aurum.economy:
    description: Grants access to /economy.
    default: op
  aurum.motd:
    description: Grants access to /motd.
    default: not op
  aurum.spawn:
    description: Grants access to /spawn.
    default: not op
  aurum.grounditemclear:
    description: Grants access to /grounditemclear.
    default: op
  aurum.setspawn:
    description: Grants access to /setspawn.
    default: op
  aurum.rules:
    description: Grants access to /rules.
    default: not op
  aurum.home:
    description: Grants access to the homes commands.
    default: op
  aurum.importzcore:
    description: Grants access to /importzcore.
    default: op
  aurum.pay:
    description: Grants access to /pay.
    default: op
  aurum.color:
    description: Allows the usage of color codes.
    default: op
  aurum.warp:
    description: Grants access to /warp and /warps.
    default: op
  aurum.setwarp:
    description: Grants access to /setwarp.
    default: op
  aurum.delwarp:
    description: Grants access to /delwarp.
    default: op
  aurum.nickname:
    description: Grants access to /nickname.
    default: op
  aurum.whois:
    description: Grants access to /whois.
    default: not op
  aurum.time:
    description: Grants access to /time.
    default: op
  aurum.weather:
    description: Grants access to /weather.
    default: op
  aurum.playerlist:
    description: Grants access to /playerlist.
    default: not op
  aurum.teleport:
    description: Grants access to /teleport.
    default: op
  aurum.teleportask:
    description: Grants access to /teleportask, /tpaccept, and /tpdeny.
    default: op
  aurum.item:
    description: Grants access to /item.
    default: op
  aurum.tellraw:
    description: Grants access to /tellraw.
    default: op
  aurum.sudo:
    description: Grants access to /sudo.
    default: op
  aurum.heal:
    description: Grants access to /heal.
    default: op
  aurum.modview:
    description: Grants access to /modview.
    default: op
  aurum.ban:
    description: Grants access to /ban, /unban, and /banlog.
    default: op
  aurum.mute:
    description: Grants access to /mute and /unmute.
    default: op
  aurum.warn:
    description: Grants access to /warn and /unwarn.
    default: op