name: Aurum
description: An essentials alternative for project poseidon.
main: org.whoisjeb.aurum.Aurum
version: 1.0.0-SNAPSHOT
authors:
  - coffeelover42
depend:
  - PermissionsEx

commands:
  aurum:
    description: Display plugin's info, or reloads its data.
    aliases: [au]
    usage: /<command> [reload|info]
    permission: aurum.aurum
  help:
    description: Displays available commands.
    aliases: [?]
    usage: /<command> [page|plugin]
    permission: aurum.help
  spawn:
    description: Warps the sender to spawn.
    usage: /<command>
    permission: aurum.spawn
  setspawn:
    description: Sets spawn to the sender's location.
    usage: /<command>
    permission: aurum.setspawn
  rules:
    description: Displays the server rules.
    usage: /<command>
    permission: aurum.rules
  discord:
    description: Links to the server's discord.
    usage: /<command>
    permission: aurum.discord
  sethome:
    description: Sets a new home at the sender's position.
    usage: /<command>
    permission: aurum.home
  home:
    description: Warps the sender to the specified home.
    aliases: [h]
    usage: /<command>
    permission: aurum.home
  delhome:
    description: Deletes the specified home.
    usage: /<command>
    permission: aurum.home
  homes:
    description: Lists the sender's homes.
    usage: /<command>
    permission: aurum.home
  warp:
    description: Teleports the sender to the specified warp.
    usage: /<command> <warp>
    permission: aurum.warp
  warps:
    description: Lists the server's warps.
    usage: /<command> <warp>
    permission: aurum.warp
  setwarp:
    description: Sets a new warp at the sender's position.
    usage: /<command> <warp>
    permission: aurum.setwarp
  delwarp:
    description: Deletes the specified warp.
    usage: /<command>
    permission: aurum.delwarp
  nickname:
    description: Changes or clears the sender's or another's nickname.
    aliases: [nick]
    usage: /<command> <set|clear> <nickname|> <player>
    permission: aurum.nickname
  whois:
    description: Tells the sender the username of an online player.
    aliases: [realname, whos]
    usage: /<command> <nickname>
    permission: aurum.whois
  time:
    description: Changes the time to the specified time.
    aliases: [settime, timeset]
    usage: /<command> <day|night|dawn|dusk>
    permission: aurum.time
  weather:
    description: Changes the weahter.
    aliases: [setweather, weatherset]
    usage: /<command> [clear|rain]
    permission: aurum.weather
  playerlist:
    description: Lists the currently online players.
    aliases: [list, who]
    usage: /<command>
    permission: aurum.playerlist
  teleport:
    description: Teleports the sender to a player or position.
    aliases: [tp]
    usage: /<command> <player|x, y, z>
    permission: aurum.teleport
  offlineteleport:
    description: Teleports the sender to the last position of an offline player.
    aliases: [offlinetp, otp]
    usage: /<command> <player>
    permission: aurum.teleport
  teleportask:
    description: Requests the target to have the sender tp to them.
    aliases: [tpa]
    usage: /<command> <player>
    permission: aurum.teleportask
  teleportaccept:
    description: Accepts the most recent tp request, or that of a specific player.
    aliases: [tpaccept]
    usage: /<command> [player]
    permission: aurum.teleportask
  teleportdeny:
    description: Denies the most recent tp request, or that of a specific player.
    aliases: [tpdeny]
    usage: /<command> [player]
    permission: aurum.teleportask
  item:
    description: Gives the sender/a player an item.
    aliases: [i]
    usage: /<command> <item> [quanity]
    permission: aurum.item
  tellraw:
    description: Prints what is typed after /tellraw.
    aliases: [tr]
    usage: /<command> <message>
    permission: aurum.tellraw
  sudo:
    description: Forces the victim to chat or run a command.
    usage: /<command> <player> <command|c:message>
    permission: aurum.sudo
  heal:
    description: Heals the sender or target.
    usage: /<command> [player]
    permission: aurum.heal
  modview:
    description: Heals the sender or target.
    aliases: [modv]
    usage: /<command> [player]
    permission: aurum.modview
  ban:
    description: Bans the specified user.
    usage: /<command> [player]
    permission: aurum.ban
  unban:
    description: Unbans the specified user.
    usage: /<command> [player]
    permission: aurum.ban
  banlog:
    description: Prints a page of the most recently banned players.
    aliases: [banl]
    usage: /<command> [page]
    permission: aurum.ban
  warn:
    description: Warns the specified user.
    usage: /<command> [player] [reason]
    permission: aurum.warn
  unwarn:
    description: Removes a warning from the specified user.
    usage: /<command> [player] [reason]
    permission: aurum.warn

permissions:
  aurum.player:
    description: Gives access to Aurum's essential commands.
    children:
      aurum.help: true
      aurum.spawn: true
      aurum.rules: true
      aurum.discord: true
      aurum.playerlist: true
      aurum.home: true
      aurum.warp: true
      aurum.teleportask: true
  aurum.aurum:
    description: Grants access to /aurum.
    default: not op
  aurum.help:
    description: Grants access to /help.
    default: not op
  aurum.spawn:
    description: Grants access to /spawn.
    default: not op
  aurum.setspawn:
    description: Grants access to /setspawn.
    default: op
  aurum.rules:
    description: Grants access to /rules.
    default: not op
  aurum.home:
    description: Grants access to the homes commands.
    default: op
  aurum.color:
    description: Allows the usage of color codes.
    default: op
  aurum.warp:
    description: Grants access to /warp and /warps.
    default: not op
  aurum.setwarp:
    description: Grants access to /setwarp.
    default: op
  aurum.delwarp:
    description: Grants access to /delwarp.
    default: op
  aurum.nickname:
    description: Grants access to /nickname.
    default: op
  aurum.whois:
    description: Grants access to /whois.
    default: not op
  aurum.time:
    description: Grants access to /time.
    default: op
  aurum.weather:
    description: Grants access to /weather.
    default: op
  aurum.playerlist:
    description: Grants access to /playerlist.
    default: not op
  aurum.teleport:
    description: Grants access to /teleport.
    default: op
  aurum.teleportask:
    description: Grants access to /teleportask, /tpaccept, and /tpdeny.
    default: op
  aurum.item:
    description: Grants access to /item.
    default: op
  aurum.tellraw:
    description: Grants access to /tellraw.
    default: op
  aurum.sudo:
    description: Grants access to /sudo.
    default: op
  aurum.heal:
    description: Grants access to /sudo.
    default: op
  aurum.modview:
    description: Grants access to /modview.
    default: op
  aurum.ban:
    description: Grants access to /ban, /unban, and /banlog.
    default: op
  aurum.warn:
    description: Grants access to /warn and /unwarn.
    default: op